### ISSUE TITLE
New abstracted, easy-to-use input system

### ISSUE THREAD

**Issue by skyne98** [sturdykeep/backbone#15]

**Comment by skyne98** [comment]
@Dev-Owl, if you want, can you replace throws with asserts when writing the tests?

**Comment by skyne98** [comment]
Next steps:
- [x] Traits that catch input system events (removes the need for overriding `containsPoint(...)` too)
- [x] Allow building input maps to map keyboard, pointer (and potentially gamepad) events into an "action" system (like in Godot)
- [x] Performance issues
- [x] Hover doesn't work when pointer is not moving
- [x] Solidify the order of trait execution (hover -> drag -> hover)

**Comment by Dev-Owl** [comment]
> @Dev-Owl, if you want, can you replace throws with asserts when writing the tests?

What exactly do you mean? If an assert fails during testing it will throw. So if we want to test for a failed one aka. expect it to fail we need to check for an exceptions.
If you want to not crash during runtime we can change all throws with asserts, I think it depends on the error and the state the system is in after it has happened.
