### ISSUE TITLE
Cannot pass custom game type

### ISSUE THREAD

**Issue by gtgalone** [sturdykeep/backbone#81]
Thank you for the nice package.

I am trying to use it.

But now in my game, I am using custom game type `HasGameRef<MyCustomGame>`

With backbone, actually I need to `PositionNode<MyCustomGame>` for HasGameRef in this node.

is it possible entire package to pass custom game type?

If you are agree, I can make pull request for this.

**Comment by Dev-Owl** [comment]
Dear @gtgalone thank you so much for looking into backbone, we are still working on it. If you check out the `rendering_and_entities` branch you will find significant changes. We want to keep the support for the Flame component system but also trying to put in next gear for performance ([see this tweet](https://twitter.com/sturdykeep/status/1638073686702825472)) 

Coming back to your topic, I would suggest that in our final version of the code the HasGameRef mixin is no longer used.
For example, a Trait no longer needs a GameRef. Actually, nothing requires a GameRef constraint anymore beside the Realm. 

```dart
class Realm<TGame extends FlameGame> extends Component with HasGameRef<TGame> {
   // Realm code ...
}
```
We don't yet know when the branch will go to main as we are still adjusting parts for the render pipeline. What I can tell you is that we will update our rouge shooter example and definitely publish a post about it on Medium.
Once we are certain that the API stays more or less stable we also will create proper documentation for everything.

**Comment by Dev-Owl** [comment]
In addition to the above, not sure how much it helps you (due to the other changes) but the below linked commit should ensure that the next version doesn't have the issue you mentioned.

https://github.com/sturdykeep/backbone/commit/6757c535e36b2b95fed377766e17982c584f8990

**Comment by gtgalone** [comment]
Hello @Dev-Owl 

That is amazing! I will close this.
